apiVersion: v1
kind: Pod
metadata:
  name: resource

spec:
  containers:
  - name: nginx
    image: nginx
    resoureces:
      # soft limit
      requests:
        memory: "68Mi"
        cpu: "100m"
      # hard limit
      limits:
        memory: "128Mi"
        cpu: "150m"