apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  
spec:
  selector: # labels are used as selectors
    project: expense
    component: backend
    environment: dev
    version: "1.1.0"
  
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80


---
apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    project: expense
    component: backend
    environment: dev
    version: "1.1.0"

spec: 
  containers:
  - name: nginx
    image: nginx