apiVersion: v1
kind: Service
metadata:
  name: nginx-lb

spec:
  type: LoadBalancer
  selector: #Labels are used as Selectors
    project: expense
    component: backend
    environment: dev
    version: "1.0.0"
    demo: lb
  
  ports:
  - protocol: TCP
    port: 80 #serviceport
    targetPort: 80
    nodePort: 3007

---

apiVersion: v1
kind: Pod
metadata:
  name: backend-lb
  labels:
    project: expense
    component: backend
    environment: dev
    version: "1.0.0"
    demo: lb

spec:
  containers:
  - name: nginx
    image: nginx